[package]
name = "nymvisor"
version = "0.1.0"
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dotenvy = { workspace = true }
humantime = "2.1.0"
humantime-serde = "1.1.1"
lazy_static = { workspace = true }
nix = { version = "0.27.1", features = ["signal"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros", "signal", "process", "sync"] }
thiserror = { workspace = true }
tracing = { workspace = true }

async-file-watcher = { path = "../../common/async-file-watcher" }
nym-bin-common = { path = "../../common/bin-common", features = ["output_format", "basic_tracing"] }
nym-config = { path = "../../common/config" }
