[package]
name = "nym-pemstore"
description = "Store private-public keypairs in PEM format"
version = "0.1.0"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
pem = "0.8"
