[package]
name = "hrycyszynvpn"
version = "1.0.0"
description = "Hrycyszyn VPN"
authors = ["Nym Technologies SA"]
license = ""
repository = ""
default-run = "hrycyszynvpn"
edition = "2021"
build = "src/build.rs"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "=1.0.0-rc.7", features = [] }

tauri-codegen = "=1.0.0-rc.5"
tauri-macros = "=1.0.0-rc.5"
#core-graphics = "=0.22.2"

[dependencies]

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.23", features = ["derive"] }
tauri = { version = "=1.0.0-rc.8", features = ["ayatana-tray", "shell-open", "system-tray"] }
tokio = { version = "1.10", features = ["sync"] }
dirs = "4.0"
bip39 = "1.0"
thiserror = "1.0"
tendermint-rpc = "0.23.0"
url = "2.2"
rand = "0.7"
eyre = "0.6.5"

aes-gcm = "0.9.4"
argon2 = { version = "0.3.2", features = ["std"] }
base64 = "0.13"
zeroize = "1.4.3"

cosmrs = { git = "https://github.com/nymtech/cosmos-rust", branch = "bugfix/account-id-length-validation", features = ["rpc", "bip32", "cosmwasm"] }
cosmwasm-std = "1.0.0-beta3"

nym-client = { path = "../../clients/native" }
client-core = { path = "../../clients/client-core" }
nym-socks5-client = { path = "../../clients/socks5" }
nym-network-requester = { path = "../../service-providers/network-requester"}
nymsphinx = { path = "../../common/nymsphinx" }
validator-client = { path = "../../common/client-libs/validator-client", features = [
    "nymd-client",
] }
mixnet-contract-common = { path = "../../common/cosmwasm-smart-contracts/mixnet-contract" }
config = { path = "../../common/config" }
coconut-interface = { path = "../../common/coconut-interface" }
credentials = { path = "../../common/credentials" }
version-checker = { path = "../../common/version-checker" }
network-defaults = { path = "../../common/network-defaults" }

fix-path-env = { git = "https://github.com/tauri-apps/fix-path-env-rs", branch = "release"}
log = "0.4"

[dev-dependencies]
ts-rs = "6.1.2"
tempfile = "3.3.0"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
