[book]
title = "Nym Operators Guide"
authors = ["Max Hampshire", "serinko"]
description = "Guides to setup Nym infrastructure"
language = "en"
multilingual = false # for the moment - ideally work on chinese, brazillian, spanish next
src = "src"
