[workspace]
members = [
    "coconut-bandwidth",
    "mixnet",
    "vesting",
    "multisig/cw3-flex-multisig",
    "multisig/cw4-group",
    "coconut-test",
    "coconut-dkg"
]

[workspace.package]
authors = ["Nym Technologies SA"]
repository = "https://github.com/nymtech/nym"
homepage = "https://nymtech.net"
documentation = "https://nymtech.net"
edition = "2021"
license = "Apache-2.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[workspace.dependencies]
cosmwasm-std = "=1.0.0"
cosmwasm-storage = "=1.0.0"
cosmwasm-schema = "=1.0.0"
cosmwasm-derive = "=1.0.0"
cw2 = { version = "=0.13.4" }
cw-storage-plus = "=0.13.4"
