name: check-merge-conflicts

# Check that the latest release branch merges into master and develop

on:
  workflow_dispatch:

jobs:
  get_release:
    runs-on: ubuntu-20.04
    needs: matrix_prep
    outputs:
      output1: ${{ steps.step2.outputs.latest_release }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Fetch all branches
        run: git fetch --all
      - name: Set output variable to latest release branch
        id: step2
        run: echo "latest_release=$(git branch -r | grep -E 'release/v[0-9]+\.[0-9]+\.[0-9]+' | tail -n 1 | sed 's/  origin\///')" >> $GITHUB_OUTPUT
  check-merge-master:
    name: Check that the release branch merges into master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check merge master
        run: |
          ./.github/workflows/support-files/git-merge-check.sh master $branch1
        env:
          branch1: ${{needs.get_release.outputs.output1}}
