name: CI for Nym API Tests

on:
  push:
    paths: 'nym-api/**'

defaults:
  run:
    working-directory: nym-api/tests

jobs:
  build:
      - name: Install Dependencies (Linux)
        run: sudo apt-get update && sudo apt-get -y install libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libudev-dev squashfs-tools
        continue-on-error: true

      - name: Use correct nvm version
        run: nvm use v18.1.0

      - name: Run tests
        run: yarn test:qa
        working-directory: nym-api/tests
