name: CI for Nym API Tests
'on':
  push:
    paths:
      - nym-api/**
defaults:
  run:
    working-directory: nym-api/tests
jobs:
  test:
    name: nym-api tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use correct nvm version
        run: nvm use v18.1.0
      - name: Install yarn
        run: yarn install
      - name: Run yarn
        run: yarn
      - name: Run tests
        run: 'yarn test:qa'
        working-directory: nym-api/tests
